// Code generated by command: go run equal_fold_asm.go -out equal_fold_amd64.s -stubs equal_fold_amd64.go. DO NOT EDIT.

package ascii

// Case-insensitive comparison of two ASCII strings (equality).
func equalFoldAVX2(a *byte, b *byte, n uintptr) int
