// Code generated by command: go run valid_asm.go -out valid_amd64.s -stubs valid_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func validPrint16(p *byte, n uintptr) int
// Requires: AVX, AVX2, SSE, SSE2, SSE4.1
TEXT ·validPrint16(SB), NOSPLIT, $0-24
	MOVQ p+0(FP), AX
	MOVQ n+8(FP), CX
	MOVQ $0x0000000000000000, DX

	// Initialize 128 bits registers.
	MOVQ   $0x1919191919191919, BX
	MOVQ   $0x7f7f7f7f7f7f7f7f, BP
	PINSRQ $0x00, BX, X0
	PINSRQ $0x01, BX, X0
	PINSRQ $0x00, BP, X1
	PINSRQ $0x01, BP, X1
	CMPQ   CX, $0x02
	JL     loop16

	// Initialize 256 bits registers.
	VPBROADCASTQ X0, Y2
	VPBROADCASTQ X1, Y3

loop32:
	// Loop until less than 32 bytes remain.
	VMOVUPS   (AX), Y4
	VMOVUPS   Y4, Y5
	VPMINUB   Y2, Y5, Y5
	VPCMPEQB  Y2, Y5, Y5
	VPMOVMSKB Y5, BX
	XORL      $0xffffffff, BX
	JNE       done
	VMOVUPS   Y4, Y5
	VPMAXUB   Y3, Y5, Y5
	VPCMPEQB  Y3, Y5, Y5
	VPMOVMSKB Y5, BX
	XORL      $0xffffffff, BX
	JNE       done
	SUBQ      $0x02, CX
	ADDQ      $0x20, AX
	CMPQ      CX, $0x02
	JGE       loop32

loop16:
	// Consume the next 16 bytes of input.
	CMPQ     CX, $0x00
	JE       valid
	MOVUPS   (AX), X2
	MOVUPS   X2, X3
	PMINUB   X0, X3
	PCMPEQB  X0, X3
	PMOVMSKB X3, BX
	XORL     $0x0000ffff, BX
	JNE      done
	MOVUPS   X2, X3
	PMAXUB   X1, X3
	PCMPEQB  X1, X3
	PMOVMSKB X3, BX
	XORL     $0x0000ffff, BX
	JNE      done

valid:
	MOVQ $0x00000001, DX

done:
	MOVQ DX, ret+16(FP)
	RET
