// Code generated by command: go run valid_print_asm.go -out valid_print_amd64.s -stubs valid_print_amd64.go. DO NOT EDIT.

package ascii

// Validates that the string only contains printable ASCII characters.
func validPrintAVX2(p *byte, n uintptr) int
