// Code generated by command: go run valid_asm.go -out valid_amd64.s -stubs valid_amd64.go. DO NOT EDIT.

package ascii

// Validates that the string only contains ASCII characters.
func validAVX2(p *byte, n uintptr) int
